version: '3.8'

services:
  webapi:
    build:
      context: .
      dockerfile: src/WebAPI/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_started
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=database;Port=5432;Database=AppDb;Username=postgres;Password=P@ssw0rd!2025#Strong;"
      Redis__Configuration: "redis:6379"
      ASPNETCORE_HTTP_PORTS: "8080;8081"  

  database:
    image: pgvector/pgvector:pg17
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "P@ssw0rd!2025#Strong"
      POSTGRES_DB: AppDb
    ports:
      - "5433:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: redis_cache
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
  redis_data:

networks:
  default:
    name: app-network
    driver: bridge